### PR TITLE
changes..........................

### PR DESCRIPTION
**Pull request by Thyraxis**
Yeah

### CODE REVIEW

**Comment by pp0236** [comment]
Nah :trollface:

**Comment by Thyraxis** [comment]
i spent over 999999 years on this code 😡

**Comment by pp0236** [comment]
> i spent over 999999 years on this code 😡

why r u not using boolean
firefox_rTXU7beZXo

**Comment by Thyraxis** [comment]
> > i spent over 999999 years on this code 😡
> 
> why r u not using boolean firefox_rTXU7beZXo

i dont like true or false. easy

**Comment by Thyraxis** [comment]
added boolean :trollface:

**Comment by Thyraxis** [comment]
i got social rejected

**Pull request closed without merging**
